import type { Metadata } from "next";
import "./globals.scss";
import Navigation from "@/components/Navigation/Navigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
			<Navigation />
			<div className="pt-32">
				{children}
			</div>
			</body>
		</html>
	);
}
